<a href="https://colab.research.google.com/github/Ohellay/arbitrary/blob/main/Matrix_product_implementation.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

[Problem 1] Matrix product is calculated manually

The matrix product  calculated by hand is given by the image below  

(\begin{matrix}
-1 & 2 & 3 \\
4 & -5 & 6 \\
7 & 8 & -9
\end{matrix})

  X

(\begin{matrix}
0 & 2 & 1 \\
0 & 2 & -8 \\
2 & 9 & -1
\end{matrix})

=

(\begin{matrix}
-1*0+2*0+3*2 & -1*2+2*2+3*9 & -1*1+2*\left(-8\right)+3*\left(-1\right) \\
4*0+\left(-5\right)*0+6*2 & 4*2+\left(-5\right)*2+6*9 & 4*1+\left(-5\right)*\left(-8\right)+6*\left(-1\right) \\
7*0+8*0+\left(-9\right)*2 & 7*2+8*2+\left(-9\right)*9 & 7*1+8*\left(-8\right)+\left(-9\right)*\left(-1\right)
\end{matrix})


=

(\begin{matrix}
6 & 29 & -20 \\
12 & 52 & 38 \\
-18 & -51 & -48
\end{matrix})

[Problem 2] Calculation by NumPy function

Using Np.matmul

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

AXB = np.matmul(a_ndarray ,b_ndarray )
print (AXB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Using Np.dot

In [ ]:
import numpy as np
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])
AXB = np.dot(a_ndarray, b_ndarray)
print(AXB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


Using @ operator

In [ ]:
AXB = a_ndarray @ b_ndarray
print(AXB)

[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]



[Problem 3] Implementation of calculation of a certain element
When doing the calculations by hand, you may have first paid attention to row 0 of matrix A and column 0 of matrix B, and then performed the following calculations.



> Multiply the (0,0) element $a_{0, 0}$ of matrix A with the (0,0) element $b_{0, 0}$ of matrix B




> Multiply the (0,1) element $a_{0, 1}$ of matrix A with the (1,0) element $b_{1, 0}$ of matrix B

> Multiply the (0,2) element $a_{0, 2}$ of matrix A with the (2,0) element $b_{2, 0}$ of matrix B

>Add all those values together









In [ ]:
import numpy as np

# Given matrices A and B
a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

# To  implement the calculation of the (0, 0)
A0XB0 = a_ndarray[0, 0] * b_ndarray[0, 0]
A0XB1 = a_ndarray[0, 1] * b_ndarray[1, 0]
A0XB2 = a_ndarray[0, 2] * b_ndarray[2, 0]

#The SUM
SUM = A0XB0 + A0XB1 + A0XB2



# Print the result
print(f"Result (0, 0): {SUM}")


Result (0, 0): 6


[Problem 4] Creating a function that performs matrix multiplication

In [56]:
import numpy as np

a_ndarray = np.array([[-1, 2, 3], [4, -5, 6], [7, 8, -9]])
b_ndarray = np.array([[0, 2, 1], [0, 2, -8], [2, 9, -1]])

def multiply_matrix(a, b):
    # To Get the dimensions of the matrices
    rows_A, cols_A = a.shape
    rows_B, cols_B = b.shape

      # The empty matrix to store the result
    result = np.zeros((rows_A, cols_B), dtype=int)

    #The  matrix multiplication is given by
    for a_row in range(rows_A):
        for b_col in range(cols_B):
            result[a_row, b_col] = sum(a[a_row, :] * b[:, b_col])

    return result

result = multiply_matrix(a_ndarray, b_ndarray)

print("Matrix A:: ")
print(a_ndarray)
print("\nMatrix B:")
print(b_ndarray)
print("\nMatrix multiplication result:")
print(result)

Matrix A:: 
[[-1  2  3]
 [ 4 -5  6]
 [ 7  8 -9]]

Matrix B:
[[ 0  2  1]
 [ 0  2 -8]
 [ 2  9 -1]]

Matrix multiplication result:
[[  6  29 -20]
 [ 12  52  38]
 [-18 -51 -48]]


The matrix product DE is defined when the number of columns of D is equal to the number of rows of E, so it cannot be calculated in this example. The code below proofs thee above statement:

In [57]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

result = multiply_matrix(d_ndarray, e_ndarray)

print("Matrix A:: ")
print(d_ndarray)
print("\nMatrix B:")
print(e_ndarray)
print("\nMatrix multiplication result:")
print(result)

ValueError: ignored

[Problem 5] Judge the input whose calculation is not defined

In [61]:
import numpy as np

d_ndarray = np.array([[-1, 2, 3], [4, -5, 6]])
e_ndarray = np.array([[-9, 8, 7], [6, -5, 4]])

if d_ndarray .shape[0] == e_ndarray .shape[1]:
  print ('The result ::' ,multiply_matrix(d_ndarray,e_ndarray))

else:
  print("The matrice does not have the same shape")


The matrice does not have the same shape


[Problem 6] Transposition

In [62]:
transpose = np.transpose(d_ndarray)

print("D_Transpose:: ")
print(transpose)

print("\n Matrix E:: ")
print(e_ndarray)

print('\n Multiplication of the matrice becomes ::' )
print(multiply_matrix(transpose,e_ndarray))



D_Transpose:: 
[[-1  4]
 [ 2 -5]
 [ 3  6]]

 Matrix E:: 
[[-9  8  7]
 [ 6 -5  4]]

 Multiplication of the matrice becomes ::
[[ 33 -28   9]
 [-48  41  -6]
 [  9  -6  45]]
